#!/bin/sh
#
# @name SkyScrub E610 Hexacopter
#
# @type Hexarotor x
# @class Copter
#
# SkyScrub V0.1
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=skyscrub}

param set-default SIM_GZ_EN 1

# ============================================================
# Six-motor control allocation
# ============================================================

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

# PX4 frame:
# +X = forward
# +Y = right
#
# Gazebo Y is reflected when converted to PX4 body coordinates.

# Motor 0 - CW
param set-default CA_ROTOR0_PX 0.000000
param set-default CA_ROTOR0_PY -0.703500
param set-default CA_ROTOR0_KM -0.05

# Motor 1 - CCW
param set-default CA_ROTOR1_PX 0.000000
param set-default CA_ROTOR1_PY 0.703500
param set-default CA_ROTOR1_KM 0.05

# Motor 2 - CW
param set-default CA_ROTOR2_PX 0.609249
param set-default CA_ROTOR2_PY 0.351750
param set-default CA_ROTOR2_KM -0.05

# Motor 3 - CCW
param set-default CA_ROTOR3_PX -0.609249
param set-default CA_ROTOR3_PY -0.351750
param set-default CA_ROTOR3_KM 0.05

# Motor 4 - CCW
param set-default CA_ROTOR4_PX 0.609249
param set-default CA_ROTOR4_PY -0.351750
param set-default CA_ROTOR4_KM 0.05

# Motor 5 - CW
param set-default CA_ROTOR5_PX -0.609249
param set-default CA_ROTOR5_PY 0.351750
param set-default CA_ROTOR5_KM -0.05


# ============================================================
# Gazebo motor mapping
# PX4 Motor 1 -> Gazebo motor 0
# ...
# PX4 Motor 6 -> Gazebo motor 5
# ============================================================

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

# Motor-speed limits for V0.1
param set-default SIM_GZ_EC_MIN1 120
param set-default SIM_GZ_EC_MIN2 120
param set-default SIM_GZ_EC_MIN3 120
param set-default SIM_GZ_EC_MIN4 120
param set-default SIM_GZ_EC_MIN5 120
param set-default SIM_GZ_EC_MIN6 120

param set-default SIM_GZ_EC_MAX1 649
param set-default SIM_GZ_EC_MAX2 649
param set-default SIM_GZ_EC_MAX3 649
param set-default SIM_GZ_EC_MAX4 649
param set-default SIM_GZ_EC_MAX5 649
param set-default SIM_GZ_EC_MAX6 649

# Temporary V0.1 estimate.
# We will tune this after validating actual loaded mass.
param set-default MPC_THR_HOVER 0.558

# Retain datalink-loss safety
param set-default NAV_DLL_ACT 2
